name: Keep Supabase Awake

on:
  schedule:
    - cron: '0 9 * * 1,4'  # At 09:00 UTC every Mon and Thu
  workflow_dispatch:        # Allows manual trigger from GitHub UI

jobs:
  ping-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @supabase/supabase-js

      - name: Run keep-alive ping
        run: |
          node -e "
            const { createClient } = require('@supabase/supabase-js');
            const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
            supabase.from('your_table').select('*').limit(1).then(({ data, error }) => {
              if (error) throw error;
              console.log('Supabase pinged successfully:', data?.length || 0, 'rows.');
            });
          "
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
