name: Keep Supabase Awake

on:
  schedule:
    - cron: '0 9 * * 1,4'  # At 09:00 UTC every Monday and Thursday
  workflow_dispatch:        # Allows manual trigger from GitHub UI

jobs:
  ping-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @supabase/supabase-js

      - name: Run keep-alive ping
        run: |
          node -e "
          const { createClient } = require('@supabase/supabase-js');
          const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
          (async () => {
            try {
              const { error } = await supabase.from('ping_test').select('*').limit(1);
              if (error) throw error;
              console.log('✅ Supabase ping successful');
            } catch (err) {
              console.error('❌ Ping failed:', err);
              process.exit(1);
            }
          })();
          "
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
